import { NextResponse } from 'next/server';

const SEEDED_CUSTOMERS = [
  {
    id: "cust-001",
    name: "Emily Watson",
    email: "emily.watson@gmail.com",
    phone: "+1 (555) 234-5678",
    treatment: "Botox (3 Areas)",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 1450,
    last_visit: "2026-07-14",
    rebooked: false,
    satisfaction_score: 4.9,
    notes: "Regular 3-month forehead and crow's feet patient. Due for rebooking."
  },
  {
    id: "cust-002",
    name: "Marcus Sterling",
    email: "marcus.s@outlook.com",
    phone: "+1 (555) 345-6789",
    treatment: "Dermal Fillers (Juvederm)",
    provider: "Dr. Julian Reed, MD",
    status: "active",
    amount_spent: 2800,
    last_visit: "2026-06-20",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "Cheek and jawline contouring. Rebooked for October maintenance."
  },
  {
    id: "cust-003",
    name: "Sophia Martinez",
    email: "smartinez@yahoo.com",
    phone: "+1 (555) 456-7890",
    treatment: "HydraFacial Deluxe",
    provider: "Elena Rostova, Aesthetician",
    status: "active",
    amount_spent: 980,
    last_visit: "2026-08-02",
    rebooked: true,
    satisfaction_score: 4.8,
    notes: "Monthly skin maintenance subscriber. Interested in Laser Genesis."
  },
  {
    id: "cust-004",
    name: "Isabella Cruz",
    email: "isabella.cruz@luxurygroup.com",
    phone: "+1 (555) 567-8901",
    treatment: "Morpheus8 RF Microneedling",
    provider: "Sarah Lin, Lead RN",
    status: "active",
    amount_spent: 3600,
    last_visit: "2026-05-18",
    rebooked: false,
    satisfaction_score: 4.7,
    notes: "Completed 2 of 3 sessions. 100+ days inactive. Priority outreach!"
  },
  {
    id: "cust-005",
    name: "Liam Patel",
    email: "lpatel@techcorp.io",
    phone: "+1 (555) 678-9012",
    treatment: "Laser Genesis Rejuvenation",
    provider: "Sarah Lin, Lead RN",
    status: "active",
    amount_spent: 1850,
    last_visit: "2026-07-29",
    rebooked: true,
    satisfaction_score: 4.9,
    notes: "Rosacea treatment program. Highly satisfied."
  },
  {
    id: "cust-006",
    name: "Olivia Chen",
    email: "olivia.chen@designstudio.com",
    phone: "+1 (555) 789-0123",
    treatment: "Botox (Masseter Slimming)",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 1200,
    last_visit: "2026-06-05",
    rebooked: false,
    satisfaction_score: 5.0,
    notes: "Teeth grinding & slimming. Past 12-week rebooking threshold."
  },
  {
    id: "cust-007",
    name: "Alexander Wright",
    email: "awright@capitalventures.com",
    phone: "+1 (555) 890-1234",
    treatment: "CoolSculpting Flanks",
    provider: "Marcus Sterling, Specialist",
    status: "active",
    amount_spent: 4200,
    last_visit: "2026-07-01",
    rebooked: true,
    satisfaction_score: 4.6,
    notes: "Follow-up scan scheduled for 90-day progress review."
  },
  {
    id: "cust-008",
    name: "Charlotte Dubois",
    email: "charlotte.d@fashionhouse.fr",
    phone: "+1 (555) 901-2345",
    treatment: "Dermal Fillers (Lip Sculpt)",
    provider: "Dr. Julian Reed, MD",
    status: "active",
    amount_spent: 1650,
    last_visit: "2026-08-10",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "Russian lip technique. Booked 6-month touch up."
  },
  {
    id: "cust-009",
    name: "James Thorne",
    email: "james.t@meridian.org",
    phone: "+1 (555) 012-3456",
    treatment: "Chemical Peel (TCA 20%)",
    provider: "Elena Rostova, Aesthetician",
    status: "active",
    amount_spent: 750,
    last_visit: "2026-05-12",
    rebooked: false,
    satisfaction_score: 4.3,
    notes: "Post-sun hyperpigmentation. Needs gentle hydration follow-up."
  },
  {
    id: "cust-010",
    name: "Victoria Kensington",
    email: "victoria.k@sovereign.co.uk",
    phone: "+1 (555) 123-7890",
    treatment: "Full Face Liquid Facelift",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 6800,
    last_visit: "2026-06-30",
    rebooked: false,
    satisfaction_score: 4.9,
    notes: "Ultra-high net worth VIP. Needs personalized executive follow-up."
  },
  {
    id: "cust-011",
    name: "Benjamin Hayes",
    email: "b.hayes@hayeslogistics.com",
    phone: "+1 (555) 234-8901",
    treatment: "Microneedling with PRP",
    provider: "Sarah Lin, Lead RN",
    status: "active",
    amount_spent: 2400,
    last_visit: "2026-07-22",
    rebooked: true,
    satisfaction_score: 4.8,
    notes: "Acne scar package 3 of 4. On track."
  },
  {
    id: "cust-012",
    name: "Mia Takahashi",
    email: "mia.t@zenithmedia.jp",
    phone: "+1 (555) 345-9012",
    treatment: "HydraFacial Platinum",
    provider: "Elena Rostova, Aesthetician",
    status: "active",
    amount_spent: 1350,
    last_visit: "2026-08-15",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "Lymphatic drainage and LED therapy booster enthusiast."
  },
  {
    id: "cust-013",
    name: "Ethan Brooks",
    email: "ebrooks@brookspartners.com",
    phone: "+1 (555) 456-0123",
    treatment: "Botox (Bro-tox Forehead)",
    provider: "Dr. Julian Reed, MD",
    status: "active",
    amount_spent: 1100,
    last_visit: "2026-05-25",
    rebooked: false,
    satisfaction_score: 4.5,
    notes: "100 days past visit. High risk of churn to competitor clinic."
  },
  {
    id: "cust-014",
    name: "Ava Sinclair",
    email: "ava.sinclair@aurora.net",
    phone: "+1 (555) 567-1234",
    treatment: "Morpheus8 Neck & Decollete",
    provider: "Sarah Lin, Lead RN",
    status: "active",
    amount_spent: 2900,
    last_visit: "2026-07-08",
    rebooked: true,
    satisfaction_score: 4.7,
    notes: "Skin laxity improvement visible. Rebooked for maintenance."
  },
  {
    id: "cust-015",
    name: "Noah Goldstein",
    email: "noah.g@quanthedge.com",
    phone: "+1 (555) 678-2345",
    treatment: "Laser Genesis & Peel Combo",
    provider: "Elena Rostova, Aesthetician",
    status: "active",
    amount_spent: 1950,
    last_visit: "2026-08-05",
    rebooked: true,
    satisfaction_score: 4.9,
    notes: "Corporate executive glow package. Very loyal."
  },
  {
    id: "cust-016",
    name: "Harper Vance",
    email: "harper.vance@vancerealty.com",
    phone: "+1 (555) 789-3456",
    treatment: "Dermal Fillers (Tear Troughs)",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 2200,
    last_visit: "2026-06-12",
    rebooked: false,
    satisfaction_score: 4.8,
    notes: "Under eye rejuvenation. Rebooking reminder due."
  },
  {
    id: "cust-017",
    name: "Lucas Bennett",
    email: "lbennett@bennettluxury.com",
    phone: "+1 (555) 890-4567",
    treatment: "CoolSculpting Abdomen",
    provider: "Marcus Sterling, Specialist",
    status: "active",
    amount_spent: 3800,
    last_visit: "2026-07-18",
    rebooked: true,
    satisfaction_score: 4.6,
    notes: "Pleased with core definition. Considering arms."
  },
  {
    id: "cust-018",
    name: "Evelyn Moreau",
    email: "evelyn.moreau@artconsortium.org",
    phone: "+1 (555) 901-5678",
    treatment: "Botox & HydraFacial Duo",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 1800,
    last_visit: "2026-08-12",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "VIP annual member. Always brings friends."
  },
  {
    id: "cust-019",
    name: "Mason Rivera",
    email: "mrivera@pacifictech.co",
    phone: "+1 (555) 012-6789",
    treatment: "Laser Tattoo Removal",
    provider: "Marcus Sterling, Specialist",
    status: "active",
    amount_spent: 1400,
    last_visit: "2026-05-30",
    rebooked: false,
    satisfaction_score: 4.4,
    notes: "Session 4 of 6. Missed August appointment."
  },
  {
    id: "cust-020",
    name: "Camila Navarro",
    email: "camila.n@valenciacapital.es",
    phone: "+1 (555) 123-0987",
    treatment: "Sculptra Aesthetic (2 Vials)",
    provider: "Dr. Julian Reed, MD",
    status: "active",
    amount_spent: 3400,
    last_visit: "2026-06-25",
    rebooked: true,
    satisfaction_score: 4.9,
    notes: "Biostimulator collagen building. Great response."
  },
  {
    id: "cust-021",
    name: "Sebastian Cole",
    email: "scole@colearchitects.com",
    phone: "+1 (555) 234-1098",
    treatment: "Botox (Forehead & Crows)",
    provider: "Dr. Julian Reed, MD",
    status: "active",
    amount_spent: 1350,
    last_visit: "2026-07-05",
    rebooked: false,
    satisfaction_score: 4.7,
    notes: "Approaching 9 weeks post-treatment."
  },
  {
    id: "cust-022",
    name: "Penelope Cruz-White",
    email: "penelope.cw@summit.org",
    phone: "+1 (555) 345-2109",
    treatment: "HydraFacial Deluxe",
    provider: "Elena Rostova, Aesthetician",
    status: "active",
    amount_spent: 850,
    last_visit: "2026-08-20",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "Loves Britenol booster for sun spots."
  },
  {
    id: "cust-023",
    name: "Daniel Kim",
    email: "daniel.kim@kimenterprises.com",
    phone: "+1 (555) 456-3210",
    treatment: "Morpheus8 Face & Neck",
    provider: "Sarah Lin, Lead RN",
    status: "active",
    amount_spent: 3200,
    last_visit: "2026-06-02",
    rebooked: false,
    satisfaction_score: 4.8,
    notes: "Needs 3rd treatment reminder before winter."
  },
  {
    id: "cust-024",
    name: "Scarlett Johansson-Lee",
    email: "scarlett.lee@cinema.com",
    phone: "+1 (555) 567-4321",
    treatment: "Dermal Fillers (Lip & Cheeks)",
    provider: "Dr. Chloe Vance, MD",
    status: "active",
    amount_spent: 3100,
    last_visit: "2026-07-28",
    rebooked: true,
    satisfaction_score: 5.0,
    notes: "High profile celebrity aesthetic patient."
  },
  {
    id: "cust-025",
    name: "Henry Cavill-Smith",
    email: "henry.cs@apexfitness.com",
    phone: "+1 (555) 678-5432",
    treatment: "CoolSculpting Submental",
    provider: "Marcus Sterling, Specialist",
    status: "active",
    amount_spent: 1900,
    last_visit: "2026-08-01",
    rebooked: true,
    satisfaction_score: 4.9,
    notes: "Double chin reduction. Exceptional contour."
  }
];

export async function GET() {
  return NextResponse.json(SEEDED_CUSTOMERS);
}
